exclude: '.venv'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
        - id: check-yaml
        - id: check-json
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
        - id: isort
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
        - id: pydocstyle
          exclude: ^alembic/versions/
          additional_dependencies:
            - toml
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.1.1
    hooks:
      - id: nbqa-black
        additional_dependencies:
          - black==21.7b0
      - id: nbqa-isort
        additional_dependencies:
          - isort==5.9.2
      - id: nbqa-flake8
        additional_dependencies:
          - flake8==3.9.2
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout